### ISSUE TITLE
Course not found error

### ISSUE THREAD

**Issue by jameshbailie** [catmanjan/anutimetable#1]
When entering COMP4630, I get the error 'course not found'. But the lecture times for this course are up on the official ANU timetable.

**Comment by catmanjan** [comment]
Support for classes with multiple courses is flaky in this case "COMP4630_S2^COMP8670_S2 Lecture01/ 001" isn't being scraped properly.

I'll add it manually for now.

**Comment by catmanjan** [comment]
fixed
