### ISSUE TITLE
Deleting any course in chrome cause display error

### ISSUE THREAD

**Issue by Yue-Tang** [catmanjan/anutimetable#117]
I'm using Chrome Version 55.0.2883.95 (64-bit).

Before deleting:
<img width="1000" alt="screen shot 2017-01-23 at 22 00 30" src="https://cloud.githubusercontent.com/assets/17894609/22207290/8a67702e-e1b9-11e6-9521-34bdd8e8cb37.png">

After deleting:
<img width="1000" alt="screen shot 2017-01-23 at 22 00 40" src="https://cloud.githubusercontent.com/assets/17894609/22206872/e0bc2890-e1b7-11e6-9490-b2ad0aefdca8.png">

**Comment by samyex6** [comment]
Fixed: #119
