### ISSUE TITLE
Cells leaking into the wrong columns

### ISSUE THREAD

**Issue by jjcrawford** [catmanjan/anutimetable#120]
I've noticed one semi-regular problem with some events leaking over into the wrong day columns:
![tablebug](https://cloud.githubusercontent.com/assets/25274625/22243113/0bc88976-e27a-11e6-995b-afee96a04a5f.png)

Seems very particular to the order that I add my courses, though. I tried adding the same courses in a different order and I didn't get the above bug but instead got the following, also problematic result:

![tablebug2](https://cloud.githubusercontent.com/assets/25274625/22243323/efe88dae-e27a-11e6-82a2-e1b1a723c1aa.png)

(PS I've been playing around with the timetabler for a few days and I'm absolutely loving it. I've been trying to implement a few of my own improvements locally that may or may not come through. Y'all are doing great work!)

**Comment by brendanmeyer** [comment]
I am seeing this as well, with the latest courses
![2019-12-09 17_38_32-Window](https://user-images.githubusercontent.com/16585315/70413648-fcba0280-1aab-11ea-8df7-a5958dab5dba.png)

**Comment by jrbecart** [comment]
I am seeing the same issue.
I tried to debug with no luck. It seems to be always with events starting after a middle of a previous event.

In @jjcrawford example it's the one encircle and with @brendanmeyer it's the first CHIN1012 (tuesday) and first MATH1005 (wednesday).

Anyone with any thought?

**Comment by jrbecart** [comment]
Finally I found the bug, in fillArray: line 323

```javascript
// replace
if (i <= hour) return;
// by
if (i < hour) return;
