### ISSUE TITLE
Problems with fractional class lengths

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#125]
The time on the ANU Timetable Builder is off by 30mins. If you look in the picture attached, you can see that the COMP1100 Lecture goes from 8:30 - 10:00 but on the timetable builder it shows 8:30 - 9:30.

Little things like this can cause a lot of problems for students who are just looking at the time listed on the left hand side of the timetable builder. If you could fix this that would be great. Amazing website btw, makes everything a lot easier!

**Comment by samyex6** [comment]
![screenshot from 2017-02-07 01-46-44](https://cloud.githubusercontent.com/assets/13520523/22672943/593872b8-ecd7-11e6-8fb0-75e4091830a9.png)

I don't see a problem? It is 8:30-10:00

**Comment by catmanjan** [comment]
Yep you're right, looks like he was confused with the 10:00 appearing as the row rather than the border
