### ISSUE TITLE
Bug in MS Edge

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#127]
` if (courseName && Course.courses.indexOf(courseName) === -1) {`

gives the error

`Object doesn't support property or method 'indexOf'`

**Comment by samyex6** [comment]
Any operations to simulate this issue?

**Comment by catmanjan** [comment]
Yeah, happens when trying to add a course on Win10 MS Edge

**Comment by samyex6** [comment]
That's weird.. Array.prototype.indexOf should be working under IE >= 9..
I'm not using Windows atm, could you test if adding the following code after revisionNum's declaration works?

```
if (!Array.prototype.indexOf) {
    Array.prototype.indexOf = function (value) {
        for (var i in this) {
            if (!this.hasOwnProperty(i)) continue;
            if (this[i] === value) return i;
        }
        return -1;
    };
}
```

**Comment by catmanjan** [comment]
Yes that does seem to fix it
