### ISSUE TITLE
Offline support, may interfere with future update

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#136]
I've added offline support with just a simple appcache manifest, I'm not sure if this is going to interfere with  updating scraped data though

This isn't really an issue, just a note that next time you scrape, can you double check that the data has all gone through properly

**Comment by samyex6** [comment]
I don't know.. it seems like everything has stopped updating, this caching method is too powerful that I can't even use code to force a update since all pages are cached, unless I clear my cache storage from F12..

**Comment by catmanjan** [comment]
The manifest file has a version number in it that I think has to be changed
when we update a file, this is annoying as we also have to manually change
the version in other places

**Comment by samyex6** [comment]
lol i think `http://anutimetable.com/manifest.appcache` itself has been cached, it worked locally though.
