### ISSUE TITLE
Suggestion: Auto Remove Clashes

### ISSUE THREAD

**Issue by lilac0** [catmanjan/anutimetable#145]
Just a suggestion for the excellent tool, have a checkbox or something to make it auto remove possibilities for tutorials or alternative lectures if a lecture without an alternative occupies the slot.
Eg.  
![image](https://user-images.githubusercontent.com/29478622/27219696-f66052aa-52c5-11e7-9006-e83a92cadad0.png)
There is no alternative for the math1116 lecture, so have an option to remove the econ and comp tutorials from the pool of available tutorials
 
Alternatively perhaps a button on various tutorials and lectures to remove them from the pool manually to help narrow down options.

**Comment by Misairu-G** [comment]
This could really be useful and reduce the page size.

**Comment by EMorf** [comment]
I'll look into it. Might be able to add a (hide) button for now to tutorials.

**Comment by lilac0** [comment]
I've noticed particularly for subjects with multiple tutorials in 1 timeslot (eg. duplicate comp labs) it can get extreme cluttered. Thanks for continuing to maintain this extremely helpful tool!
 
![image](https://user-images.githubusercontent.com/29478622/36241384-190cfd12-126a-11e8-9eb5-f0f9e957f3a7.png)
[Pictured: Drowning in choices]

**Comment by EMorf** [comment]
![image](https://user-images.githubusercontent.com/8428597/36296549-de72b9b6-1341-11e8-8563-2f84f0038e04.png)

I've added a hide button in the latest update. Enjoy :)
