### ISSUE TITLE
Access from China?

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#150]
> Hi Jan,
> Trying to access the timetable builder from china on VPN but it is still not working for me.
> 
> Please let me know if this can be solved.
> 
> Thanks so much,
> Natasha
> Sent from my iPhone

**Comment by samyex6** [comment]
Weird.. According to [http://www.greatfirewallofchina.org/index.php?siteurl=http%3A%2F%2Fanutimetable.com%2F](url), also other people in China, it shouldn't be blocked from accessing the site itself with or without VPN -.-

**Comment by catmanjan** [comment]
Yep I suspect user error, closing.
