### ISSUE TITLE
report bug?

### ISSUE THREAD

**Issue by Re0anu** [catmanjan/anutimetable#160]
i cant find comp1730 wed 11am-1pm lab group

**Comment by samyex6** [comment]
![a](https://user-images.githubusercontent.com/13520523/28553059-fb7ac1c0-7134-11e7-9385-6db7b1d7bc36.png)
It should be there, please make sure the data source is up-to-date by checking the time of the data source (at the right top of the page, currently 23rd of July) or clear the localstorage.
