### ISSUE TITLE
BIOL1003 timetable is incorrect

### ISSUE THREAD

**Issue by BiologyJoy** [catmanjan/anutimetable#207]

**Comment by EMorf** [comment]
Yup, it seems that one lecture appears on the wrong day because the timetable thinks the replacement lecture slot is the regular lecture slot. I'll fix this issue manually, expect it to be fixed in the update later today.

**Comment by BiologyJoy** [comment]
Thanks ☺

Joy McDermid
Senior Coursework Student Administrator
Biology Teaching and Learning Centre (BTLC)
Research School of Biology
College of Science
Gould Wing (Bldg 116) Linnaeus Way
The Australian National University
Canberra ACT 2600 Australia
T: + 61 2 6125 9090
E: joy.mcdermid@anu.edu.au<mailto:joy.mcdermid@anu.edu.au>

W: http://biology.anu.edu.au/

CRICOS Provider #00120C

**Comment by EMorf** [comment]
Hi Joy, I fixed the wrong lecture slot. Should be fine in the latest update. 😀
