### ISSUE TITLE
Image export display error

### ISSUE THREAD

**Issue by Aerijo** [catmanjan/anutimetable#214]
How it appears on the website
<img width="414" alt="screen shot 2018-02-20 at 11 05 10 pm" src="https://user-images.githubusercontent.com/22167388/36423106-ba396618-1692-11e8-9a53-e0daa573b9f5.png">

How it appears on the image created by `Export .png`
<img width="414" alt="screen shot 2018-02-20 at 11 07 02 pm" src="https://user-images.githubusercontent.com/22167388/36423122-cd5d7cca-1692-11e8-9a8a-8fcddd29b607.png">

As seen in the screenshot, the course I experience this with is MATH2222. My others are fine, even ones with similar box sizes and contents. E.g., a side by side comparison of entries in the same exported image.
<img width="727" alt="screen shot 2018-02-20 at 11 10 01 pm" src="https://user-images.githubusercontent.com/22167388/36423240-37c89e14-1693-11e8-9839-a9b0cd7b5daf.png">

I guess this could be caused by `html2canvas` though, so I'm not sure if it can be fixed here.

**Comment by EMorf** [comment]
Interesting. Can you try refreshing the page, then exporting? I thought I fixed this issue but evidently not 😣

**Comment by Aerijo** [comment]
No luck. I closed the tab, cleared `Cookies and other site data` and `Cached images and files` in chrome, and then opened the google search result in a new tab. Making MATH2222 my only class, the exported PNG still overlapped onto the second line in each text box.

**Comment by EMorf** [comment]
Fair enough, thanks for this :) it has to be the html2canvas library then. I'll look into it this afternoon.

On 21 Feb. 2018 12:31, Benjamin Gray <notifications@github.com> wrote:

No luck. I closed the tab, cleared Cookies and other site data and Cached images and files in chrome, and then opened the google search result in a new tab. Making MATH2222 my only class, the exported PNG still overlapped onto the second line in each text box.

**Comment by EMorf** [comment]
@Aerijo It seems that other html2canvas users are having [similar ](https://github.com/niklasvh/html2canvas/issues/1324)[issues](https://github.com/niklasvh/html2canvas/issues/1446) so it's a library thing. As a temporary fix, you can resize the window width so that the word "Tutorial" appears first on the second line, like this: 
![image](https://user-images.githubusercontent.com/8428597/36471653-5160c878-1743-11e8-9fe9-73849c1808f2.png)

Then, exporting as a .png should work fine:
![timetable 18](https://user-images.githubusercontent.com/8428597/36471731-a3e2bfca-1743-11e8-8bcc-9445f2046f00.png)


I'll raise an issue with the library dev, hopefully this'll get fixed soon.

**Comment by Aerijo** [comment]
Yes, doing so resolves the issue.

**Comment by rappad** [comment]
still facing this issue

**Comment by Aerijo** [comment]
@rappad Did resizing the window work as a temporary fix? The issue was closed here because it was caused by an external dependency.

**Comment by porzellangott** [comment]
Hi,

 I have similiar issues. It works fine with Google Chrome. It seems the text bounds are not calcuated correct with IE. Google Chrome supports range bounds and IE doesn't, so it uses wrapper, which is sometimes not correct:

`var getWrapperBounds = function getWrapperBounds(node, scrollX, scrollY) {
    var wrapper = node.ownerDocument.createElement('html2canvaswrapper');
    wrapper.appendChild(node.cloneNode(true));
    var parentNode = node.parentNode;
    if (parentNode) {
        parentNode.replaceChild(wrapper, node);
        var bounds = (0, _Bounds.parseBounds)(wrapper, scrollX, scrollY);
        if (wrapper.firstChild) {
            parentNode.replaceChild(wrapper.firstChild, wrapper);
        }
        return bounds;
    }
    return new _Bounds.Bounds(0, 0, 0, 0);
};`
