### ISSUE TITLE
Stop pulling replacement activities

### ISSUE THREAD

**Issue by EMorf** [catmanjan/anutimetable#234]
I've had a few emails of students confusing make-up and regular tutorials. In particular, the scrapper is not able to differentiate between them and pulls both. So tutorials that occur only once as makeups appear to be regular tutorials on our timetable. Would it be possible to prevent the scrapper from storing activities that occur only once per semester?

**Comment by samyex6** [comment]
It's possible if the scraper also fetches the `week` field from the source and we can implement a feature to show classes on a given week only.

Can you provide a course which such situations occur?

**Comment by EMorf** [comment]
Here's the whole email:

Dear Emmanuel,

 

We have received many complaints that students are getting confused when they are using the ANU Timetable Builder http://anutimetable.com/.

 

Some classes are timetabled as makeup classes for some specific weeks only, however, the ANU Timetable Builder does not display the week/s that the makeup classes are timetabled. For example (screen shot shown below), Friday 9-10am for POLS2009 is a makeup Tutorial for one week only taken place last week.  

 

Sometimes when room changes being updated to the timetable, the ANU Timetable Builder did not reflect the updates timely, as a result, it has caused further confusions.

 

It will be great if you can please remove the room information from the ANU Timetable Builder, so the students can check the ANU official Timetable website for room information and hence they are able to view the actual weeks for the classes being timetabled.

 

Please let know me if this kind of update is possible. Many thanks.

**Comment by EMorf** [comment]
and the screenshot:

![image001](https://user-images.githubusercontent.com/8428597/37076499-fe261fbc-222a-11e8-8481-5a8dfa9c0a51.png)

**Comment by EMorf** [comment]
```tds.eq(6)``` has the weeks, which can be grabbed by the regex ``` ((\d+-\d+)+,?)+``` if it's any help.

**Comment by samyex6** [comment]
Cheers I'll try implement it on the weekend

**Comment by samyex6** [comment]
Cool I'll try implement it on the weekend.

**Comment by samyex6** [comment]
Implemented. However it still requires some testing. 

The JSON structure now has an additional array at index 4 which stores the starting date and ending date of the semester, it's used to calculate the week offset and display them from 1 instead of week of the year. 
Also each class now has `note` (additional info like 'makeup tutorial cuz of flooding', it'll appear as a hoverable button) and `weeks` (e.g. 8,10-12,14) field.

**Comment by EMorf** [comment]
Wow, nicely done @samyex6 . I've fixed some bugs I found and now I'm comparing random courses with the official timetable, so far it looks like it's perfectly accurate.

**Comment by samyex6** [comment]
The source that's being pushed to the website is outdated and caused the website to be broken, you might want to update it asap

**Comment by EMorf** [comment]
On it, almost done.

**Comment by samyex6** [comment]
somehow tutorial choosing doesn't work anymore

**Comment by EMorf** [comment]
Yep, I'm aware. I just pushed to avoid the website being down, the fix is coming soon. Just testing now.

**Comment by EMorf** [comment]
#242

**Comment by EMorf** [comment]
Looks like there's still an issue due to  tutorials being set as not having alternatives, which overwrites the saved ID which is chosen by the user... I'll investigate more tomorrow

**Comment by mdchia** [comment]
The week switcher means that tutorials that appear later in the semester fail to appear on earlier weeks - current hotfix is to default to display to week 2, but there's probably a better way of handling this

**Comment by BishopOfTurkey** [comment]
Haven't had anyone have this issue recently
