### ISSUE TITLE
ics export broken on http://anutimetable.com/

### ISSUE THREAD

**Issue by Alwinius** [catmanjan/anutimetable#258]
To reproduce:
- Select courses on http://anutimetable.com/
- Press "Export .ics"

Expected behaviour:
- ics file containing all events is returned

Actual behaviour:
- Every weekly event is returned only once and with a completely wrong date from semester 1
- file name is "anu_s1_timetable.ics"

**Comment by Alwinius** [comment]
This has been fixed in https://github.com/mdchia/anutimetable/commit/27305e52b57af5f36180595917aca3a245fd75f1

**Comment by tomxu93** [comment]
Bug report: The fix is not reflected on the website. Please have a look again, thanks!

**Comment by mdchia** [comment]
This fix is available at https://mdchia.github.io/anutimetable/ - we'll try to line up the forks at some point but that's the dev fork

**Comment by tomxu93** [comment]
Great, got it! Thanks a lot!

**Comment by mdchia** [comment]
Forks merged as of https://github.com/catmanjan/anutimetable/commit/134fbdaa7b6d002d2053bcdbc81d0dda8983dd06
