### ISSUE TITLE
Need to update the course list to include latest tutorial information

### ISSUE THREAD

**Issue by Davidzyc101** [catmanjan/anutimetable#260]
Now most of the courses in semester 2 have been up in ANU server with **tutorial** time updated. Please update them so that we could include the tutorials in. Cheers.

**Comment by samyex6** [comment]
Right now this repo is not being actively maintained, for the newest update please check here: https://mdchia.github.io/anutimetable/

**Comment by samyex6** [comment]
It seems like the problem you are having is that you haven't switched weeks.
The data given by official website states that tutorials start in Week 2, if you switch the week (the switcher is left to "Monday") to 2 you can see those tutorials. 
It might not be somewhat intuitive but we'll try to improve the UI in the future.
Please check if this is the case.

Anyway, I have just updated the database in **this repo**.

**Comment by mdchia** [comment]
Rescraped for 2019 Sem 1, and starts with a view to week 2 by default. Should be fixed for now.
