### ISSUE TITLE
ANTH1003

### ISSUE THREAD

**Issue by littlecat16** [catmanjan/anutimetable#261]
The time for ANTH1003 lecture is incorrect. You have Monday 1-2pm @ Barry Drive

It's actually Wednesday 8-10am at RN Robertson Lecture Theatre

**Comment by littlecat16** [comment]
The tute times are also incorrect

**Comment by mdchia** [comment]
This has been fixed on https://mdchia.github.io/anutimetable/, we'll try to bring updates over at some point

**Comment by littlecat16** [comment]
Great thanks :)

**Comment by mdchia** [comment]
Should be fixed for next sem
