### ISSUE TITLE
Sync needed

### ISSUE THREAD

**Issue by samyex6** [catmanjan/anutimetable#264]
Sync between https://github.com/mdchia/anutimetable and this repo might be essential to prevent confusion and keep maintainability.
Alternatively, we can just make changes in this repo? 
@mdchia

**Comment by catmanjan** [comment]
i did a merge

**Comment by mdchia** [comment]
Sync'd for 2019 sem 1

**Comment by cjchristopher** [comment]
There have been some updates since the current pull on 16 Jan - a resync would be appreciated,
