### ISSUE TITLE
still on semester 1 - iCal

### ISSUE THREAD

**Issue by pheas** [catmanjan/anutimetable#356]
I think the calendar functions are still set to semester 1 dates so when you import to a calendar the tunes and lectures etc show up between March and June 2020. Wondering if that can be adjusted to Sem 2 dates

**Comment by pl4nty** [comment]
This was supposed to be fixed by #352, can you attach your .ics file?

**Comment by pheas** [comment]
It says it doesn't support .ics files

**Comment by pheas** [comment]
also on the home page it still has --- (Unofficial) ANU Timetable Planner **2020S1** (offline compatible)
not sure whats going on there

**Comment by BishopOfTurkey** [comment]
Try reloading the cache. Sometimes it gets stuck with an old version of the page.

**Comment by pheas** [comment]
yep - that seems to have fixed it. cheers!
