### ISSUE TITLE
ICS format invalid

### ISSUE THREAD

**Issue by harry-hart** [catmanjan/anutimetable#365]
The ICS file exported doesn't seem to be valid, it looks like you have a bug when formatting the "EXDATE" string for "holiday2". I have tried importing it into google calendar and protoncalendar, the google error is not very helpful, but included for completeness:
![image](https://user-images.githubusercontent.com/75236748/108017067-1d92c600-7068-11eb-8efd-77b1bf987006.png)

ProtonCalendar bug (more helpful):
![image](https://user-images.githubusercontent.com/75236748/108017108-34391d00-7068-11eb-8055-35dfafecf903.png)

ICS File in question:
[anu_s2_timetable.ics.txt](https://github.com/catmanjan/anutimetable/files/5986013/anu_s2_timetable.ics.txt)

**Comment by Will7838** [comment]
I'm having the same problem. I was able to import into the Outlook calender, but some of the dates and times are incorrect (see attached image). It seems all events from Wednesday to Friday are set to start at 11AM, which is incorrect.

I don't have any classes today (Friday 19th).

![ical issue 2](https://user-images.githubusercontent.com/13763780/108441514-5ff71580-72a9-11eb-88b2-2b34b1e0ed53.jpg)
