### ISSUE TITLE
[Feature Request] Current Semester Auto-detect 

### ISSUE THREAD

**Issue by Lutra-Fs** [catmanjan/anutimetable#378]
The website and calendar need to be updated when the semester changes. The progress should be automatic.

**Comment by BishopOfTurkey** [comment]
Hi Lutra, I don’t have time to set this up but I’m happy to accept a merge request.

**Comment by Lutra-Fs** [comment]
I will make a GitHub action for this. But it will not come in the next following months. I will leave more details soon.

**Comment by Lutra-Fs** [comment]
Hi @BishopOfTurkey,
When does this project change its semester settings?

**Comment by BishopOfTurkey** [comment]
Usually a couple of weeks before semester.

The timetable URL also changes each year.

**Comment by Lutra-Fs** [comment]
Doing that now. I want to create a couple of python file. One for scrape (ANU’s calendar), one for modification. To make modification easier, I will create template documents for index.html timetable.js and scraper.py. The modifier will generate deployment documents from template documents. I am also considering adding the auto-archive function, I noticed there are no archive for 2020s2 and 2021s1. Or we can automatically put a tag for the latest commit of a semester?
2021年8月7日 +1000 08:27 Obi Symons ***@***.***>，写道：

**Comment by Lutra-Fs** [comment]
Fix it. When you solve the conflict in timetable.js, you keep the old version and the new version so they cause the error.

**Comment by Lutra-Fs** [comment]
I think you may need to revert your reversion cause I cannot merge my old commit to this repo, they already exist.

**Comment by BishopOfTurkey** [comment]
Should be all merged now, thanks for doing this!
