### ISSUE TITLE
For ECON8069 Time

### ISSUE THREAD

**Issue by u7373590** [catmanjan/anutimetable#379]
Could you update the tutorial time for the Econ8069, there are several tutorial groups missed after group 13 on the timetable.

**Comment by BishopOfTurkey** [comment]
Hi, Looks like it shows all the groups up to 17
![image](https://user-images.githubusercontent.com/12539475/127854033-06bf954c-3a9d-40ad-b61c-435f1e1908c6.png)

**Comment by u7373590** [comment]
I choose group 19 at the period time Thursday 4-5 pm. Maybe it has some error on the timetable.  ( Refer to the screenshot below)
Thank you!


<img width="1109" alt="Screen Shot 2021-08-02 at 19 29 17" src="https://user-images.githubusercontent.com/88315314/127854955-4e90e025-1b5b-4643-9970-bc9556b926c4.png">

**Comment by BishopOfTurkey** [comment]
Looking at the official timetable those groups aren't reflected on the timetable.
![image](https://user-images.githubusercontent.com/12539475/127856406-b8dc9394-c5ce-480e-ba46-556d6108dc9a.png)
