### ISSUE TITLE
Add "Timetable current as of" note

### ISSUE THREAD

**Issue by caitelatte** [catmanjan/anutimetable#4]
If your web scraper is run manually, it can be easy for it to get out of date if they do updates without you noticing (all the time). @bshlgrs had this problem last year and got an email from ANU Timetabling when they noticed his was out of date. It'll also solve the issue of when you haven't updated your information when a new semester begins. :)

It's not something I can add myself without figuring out your data sources or there'd be a PR attached. :)

**Comment by catmanjan** [comment]
Good catch, I'll commit the scraper - last scrape was 2015-07-04

**Comment by bshlgrs** [comment]
Most obvious way to "commit the scraper” is to have the timetable webpage load the URL of the data and parse it whenever the page is loaded.

**Comment by catmanjan** [comment]
Not sure what you mean there @bshlgrs, are you talking about file metadata?
