### ISSUE TITLE
Make lesson style fit to whole block, see screenshot

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#40]
I think it would be a lot clearer if the lesson style was applied to the timeslot rather than the lesson container.

![untitled](https://cloud.githubusercontent.com/assets/137350/12225096/6185687e-b856-11e5-88d8-fcf621f73a3c.png)

**Comment by catmanjan** [comment]
Has an issue where the color remains when a class is removed, need to add
```
.timeslot:empty {
	background-color : transparent !important;
}
```

**Comment by samyex6** [comment]
Overwrite this without actually deleting the lesson-style-* class will cause issues when adding courses later (multiple lesson-style-*).
So I chose this fix on line 223 instead:
```javascript
$(this).parent().removeClass(function(i, c) {
    return (c.match(/(^|\s)lesson-style-\d+/g) || []).join(' ');
}).empty();
```

**Comment by catmanjan** [comment]
Hmm still seems to not be working

![image](https://cloud.githubusercontent.com/assets/137350/12226018/ad196e4e-b869-11e5-908d-8b1598e53596.png)
