### ISSUE TITLE
Remove slideDown, slideUp effects

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#46]
In some browsers it creates strange behavior, I think people would prefer to just have their courses appear instantly

**Comment by catmanjan** [comment]
I did a ctrl+f for slideUp and slideDown and replaced them with show/hide accordingly, but when removing a course there is another effect applied, not sure where to disable that

**Comment by catmanjan** [comment]
Needed to include timeout along with complete function for hide() to be instant

**Comment by samyex6** [comment]
hide() is just a toggle to display: hidden so I think it should be close to instant?

**Comment by catmanjan** [comment]
Yeah that's what I thought, but it seems doing ```hide(function() { ... })``` was causing an animation to play, but ```hide(0, function() { ... })``` was not.
