### ISSUE TITLE
"Large Group Teaching" aren't choosable

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#57]
Received the following email:

> Whilst I was making my timetable I noticed some options didn’t have the ‘choose’ feature despite them being duplicates. This is the case for the BIOL1008 Large Group Teaching and all the STAT1008 lectures.

**Comment by catmanjan** [comment]
My guess is that the following function isn't working as expected:

```
var isCompulsory = function (string) {
    // Best guess as to whether the class is compulsory
    if (string.toLowerCase().indexOf('lecture') > -1
        || string.toLowerCase().indexOf('group teaching') > -1
        || string.toLowerCase().indexOf('seminar') > -1) {
        return true;
    }
}
```

**Comment by samyex6** [comment]
Actually I think we should remove this function since the compulsory courses are sometimes choosable.
I'll push a temporary fix along with the newest timetable.
