### ISSUE TITLE
Download as .ics broken in Safari

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#65]
Received the following email:

> After finalizing my timetable on Safari, clicking on the “Download as .ics” button results in this error message: 
> Safari can't open the page "data:blob:http://anutimetable.com/5fe43ace-ccc6-4284-823c-edc2678e5a8d”. The error is: “The operation couldn’t be completed. (kCFErrorDomainCFNetwork error –10.)” (kCFErrorDomainCFNetwork:-10)

I will have a look at this on the weekend, however this issue has existed since the start of the project so I suspect it will be another dead end.

**Comment by samyex6** [comment]
Safari 5 doesn't support Blob constructor, I tried a PHP solution it worked locally but unfortunately git doesn't support PHP ;A;
Maybe consider try { download() } & catch { /* flash alternative */ }?

**Comment by EMorf** [comment]
Tested on Safari on two different macs, seems to not be an issue anymore. Closing the thread.
