### ISSUE TITLE
.ics file generated cannot be read by Calendar for Mac

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#66]
Received an email

> I used Firefox and it was able to successfully download an ics file, but the ics file cannot be imported into the Calendar app for Mac. I tried several times but it still can't be imported nor read by the Cal app.

**Comment by MateusZitelli** [comment]
:+1: The ics files are not valid.

**Comment by catmanjan** [comment]
Some calendar applications do not parse start of line whitespace, will need patch now

**Comment by catmanjan** [comment]
@samyex6 this may have been caused by HTML autoformatting, need to ensure that the ICS template tags don't get formatted

**Comment by catmanjan** [comment]
fixed #88
