### ISSUE TITLE
two glitches found in anutimetable.com

### ISSUE THREAD

**Issue by catmanjan** [catmanjan/anutimetable#93]
> For COMP3420 three lectures, you are only able to choose one of them( if you choose one the rest of them will disappear like choosing tutorials)
> 
> And COMP2100 Lab is 1 hour long not 2 hours.
> 
> btw: anutimetable.com is 1000 times better than the timetable system provided by  ANU

**Comment by samyex6** [comment]
Both issues require ANU to fix their data source, I had sent an email to them, pending for a fix.
